/* tslint:disable */
// This file is generated
// Do not edit this file

import type * as whatsapp from "./whatsapp/index";
export * as whatsapp from "./whatsapp/index";

export type Channels = {
  whatsapp: whatsapp.ChannelWhatsapp;
}
